@WoWStats.API_HostAddress = http://localhost:5289


GET {{WoWStats.API_HostAddress}}/Authorization/authorize
Accept: application/json

###

GET {{WoWStats.API_HostAddress}}/Profile/summary
Accept: application/json

###